on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  heroku_git_deploy_job:
      runs-on: ubuntu-latest
      name: Git Deploy job- A job to deploy django app to heroku using git

      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Install requirements # install application requirements
          run: pip install -r requirements.txt

        - name: Run Test # running tests
          run: python manage.py test
        - name: Deploy django to heroku
          uses: nyakaz73/heroku-django-deploy@v0.68 
          with: 
            heroku_app_name : int-online-clothing-store
            heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
            heroku_email_address: 'hopemichael720@gmail.com'
            use_git: true
